version: '3'

services:
  codingtest:
    build:
        context: .
        dockerfile: ./codingtest/Dockerfile
    expose:
       - 8081
    ports:
      - "8081:8080"
    volumes:
      - ./codingtest/build/libs/:/codingtest/
    depends_on:
      - postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/sia?useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: ksl2950
      SPRING_DATASOURCE_PASSWORD: rlathddl
    restart: always
    stdin_open: true
    tty: true

  postgresql: 
    image: postgis/postgis
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "sia"
      POSTGRES_USER: "ksl2950"
      POSTGRES_PASSWORD: "rlathddl"
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting